name = "weekly-wallet-monitor"
main = "src/index.js"
compatibility_date = "2023-10-30"
compatibility_flags = ["nodejs_compat"]
account_id = "a928f4bf274d697272e1ddf90cb49798"

[triggers]
crons = ["0 8 * * *"]

[vars]
FRONTEND_URL = "https://weekly-wallet.pages.dev"
BACKEND_URL = "https://weekly-wallet-backend.renanbuiatti14.workers.dev"
