name = "weekly-wallet-backend"
main = "src/index.js"
compatibility_date = "2023-10-30"
account_id = "a928f4bf274d697272e1ddf90cb49798"

[[r2_buckets]]
binding = "WEEKLY_WALLET_BUCKET"
bucket_name = "weekly-wallet-data"
preview_bucket_name = "weekly-wallet-data-preview"
